// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hrconnectbackend.Data;

#nullable disable

namespace hrconnectbackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241226171046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hrconnectbackend.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<TimeOnly>("ClockIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("ClockOut")
                        .HasColumnType("time");

                    b.Property<DateOnly>("DateToday")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Auth", b =>
                {
                    b.Property<int>("AuthEmpId")
                        .HasColumnType("int");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("bit");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("VerificationCode")
                        .HasColumnType("int");

                    b.HasKey("AuthEmpId");

                    b.ToTable("Auths");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("hrconnectbackend.Models.EducationBackground", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EducationBackgrounds");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("hrconnectbackend.Models.EmployeeInfo", b =>
                {
                    b.Property<int>("EmployeeInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeInfoId");

                    b.ToTable("EmployeesInfo");
                });

            modelBuilder.Entity("hrconnectbackend.Models.LeaveApplication", b =>
                {
                    b.Property<int>("LeaveApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveApplicationId"));

                    b.Property<DateOnly>("AppliedDate")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaveApplicationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveApplications");
                });

            modelBuilder.Entity("hrconnectbackend.Models.LeaveApproval", b =>
                {
                    b.Property<int>("LeaveApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveApprovalId"));

                    b.Property<DateOnly?>("ApprovedDate")
                        .HasColumnType("date");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaveApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("LeaveApprovalId");

                    b.HasIndex("LeaveApplicationId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("LeaveApprovals");
                });

            modelBuilder.Entity("hrconnectbackend.Models.OTApplication", b =>
                {
                    b.Property<int>("OTApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OTApplicationId"));

                    b.Property<DateOnly>("AppliedDate")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OTApplicationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("OTApplications");
                });

            modelBuilder.Entity("hrconnectbackend.Models.OTApproval", b =>
                {
                    b.Property<int>("OTApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OTApprovalId"));

                    b.Property<DateOnly>("ApprovedDate")
                        .HasColumnType("date");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OTApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("OTApprovalId");

                    b.HasIndex("OTApplicationId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("OTApprovals");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Payroll", b =>
                {
                    b.Property<int>("PayrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayrollId"));

                    b.Property<double>("Bonus")
                        .HasColumnType("float");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("date");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("PayrollId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DaysOfWorked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeShiftId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeOut")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeShiftId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Attendance", b =>
                {
                    b.HasOne("hrconnectbackend.Models.Employee", "Employee")
                        .WithMany("Attendance")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Auth", b =>
                {
                    b.HasOne("hrconnectbackend.Models.Employee", "Employee")
                        .WithOne("Auth")
                        .HasForeignKey("hrconnectbackend.Models.Auth", "AuthEmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Department", b =>
                {
                    b.HasOne("hrconnectbackend.Models.Supervisor", "Supervisor")
                        .WithOne("Department")
                        .HasForeignKey("hrconnectbackend.Models.Department", "ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("hrconnectbackend.Models.EducationBackground", b =>
                {
                    b.HasOne("hrconnectbackend.Models.EmployeeInfo", "EmployeeInfo")
                        .WithMany("EducationBackground")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeInfo");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Employee", b =>
                {
                    b.HasOne("hrconnectbackend.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("hrconnectbackend.Models.Supervisor", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("hrconnectbackend.Models.EmployeeInfo", b =>
                {
                    b.HasOne("hrconnectbackend.Models.Employee", "Employee")
                        .WithOne("EmployeeInfo")
                        .HasForeignKey("hrconnectbackend.Models.EmployeeInfo", "EmployeeInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("hrconnectbackend.Models.LeaveApplication", b =>
                {
                    b.HasOne("hrconnectbackend.Models.Employee", "Employee")
                        .WithMany("LeaveApplication")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("hrconnectbackend.Models.LeaveApproval", b =>
                {
                    b.HasOne("hrconnectbackend.Models.LeaveApplication", "LeaveApplication")
                        .WithOne("LeaveApproval")
                        .HasForeignKey("hrconnectbackend.Models.LeaveApproval", "LeaveApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hrconnectbackend.Models.Supervisor", "Supervisor")
                        .WithMany("LeaveApprovals")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaveApplication");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("hrconnectbackend.Models.OTApplication", b =>
                {
                    b.HasOne("hrconnectbackend.Models.Employee", "Employee")
                        .WithMany("OTApplication")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("hrconnectbackend.Models.OTApproval", b =>
                {
                    b.HasOne("hrconnectbackend.Models.OTApplication", "OTApplication")
                        .WithOne("OTApproval")
                        .HasForeignKey("hrconnectbackend.Models.OTApproval", "OTApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hrconnectbackend.Models.Supervisor", "Supervisor")
                        .WithMany("OTApprovals")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OTApplication");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Payroll", b =>
                {
                    b.HasOne("hrconnectbackend.Models.Employee", "Employee")
                        .WithMany("Payroll")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Shift", b =>
                {
                    b.HasOne("hrconnectbackend.Models.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Supervisor", b =>
                {
                    b.HasOne("hrconnectbackend.Models.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("hrconnectbackend.Models.Supervisor", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("hrconnectbackend.Models.Employee", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("Auth")
                        .IsRequired();

                    b.Navigation("EmployeeInfo")
                        .IsRequired();

                    b.Navigation("LeaveApplication");

                    b.Navigation("OTApplication");

                    b.Navigation("Payroll");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("hrconnectbackend.Models.EmployeeInfo", b =>
                {
                    b.Navigation("EducationBackground");
                });

            modelBuilder.Entity("hrconnectbackend.Models.LeaveApplication", b =>
                {
                    b.Navigation("LeaveApproval");
                });

            modelBuilder.Entity("hrconnectbackend.Models.OTApplication", b =>
                {
                    b.Navigation("OTApproval")
                        .IsRequired();
                });

            modelBuilder.Entity("hrconnectbackend.Models.Supervisor", b =>
                {
                    b.Navigation("Department")
                        .IsRequired();

                    b.Navigation("LeaveApprovals");

                    b.Navigation("OTApprovals");

                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
